# Generated by Django 3.2 on 2021-04-22 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofileinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userprofileinfo',
            table='userprofileinfo',
        ),
    ]
