# Generated by Django 3.2 on 2021-04-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authDjango', '0002_auto_20210422_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_email',
            new_name='email',
        ),
    ]
